version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gazin
      - DB_USERNAME=tiago
      - DB_PASSWORD=123456
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=teste123
      - MYSQL_DATABASE=projetogazin
      - MYSQL_USER=tiago
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
